version: "3.9"
services:
    cassandra-node1:
        image: cassandra:latest
        container_name: cassandra-node1
        ports:
            - "9042:9042"
        environment:
            - CASSANDRA_CLUSTER_NAME=CommentCluster
            - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

    cassandra-node2:
        image: cassandra:latest
        container_name: cassandra-node2
        environment:
            - CASSANDRA_CLUSTER_NAME=CommentCluster
            - CASSANDRA_SEEDS=cassandra-node1
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
